services:
  api-gateway:
    image: docker pull ghcr.io/scholarx-assesment/api-gateway:latest
    ports:
      - "8000:8000"
    environment:
      STUDENT_SERVICE_URL: "http://student-service:5001"
      CLASS_SCHEDULE_SERVICE_URL: "http://class-schedule-service:5002"
      EMAIL_SENDER_SERVICE_URL: "http://email-sender-service:5003"
    depends_on:
      - student-service
      - class-schedule-service
      - email-sender-service
    networks:
      - app-network

  student-service:
    image: docker pull ghcr.io/scholarx-assesment/student-service:latest 
    ports:
      - "5001:5001"
    networks:
      - app-network

  class-schedule-service:
    image: docker pull ghcr.io/scholarx-assesment/class-schedule-service:latest
    ports:
      - "5002:5002"
    networks:
      - app-network

  email-sender-service:
    image: docker pull ghcr.io/scholarx-assesment/notification-service:latest
    ports:
      - "5003:5003"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
