services:
  api-gateway:
    container_name: api-gateway
    image: ghcr.io/scholarx-assesment/api-gateway:latest
    ports:
      - "8000:8000"
    environment:
      STUDENT_SERVICE_URL: "http://student-service:5001"
      CLASS_SCHEDULE_SERVICE_URL: "http://class-schedule-service:5002"
      EMAIL_SENDER_SERVICE_URL: "http://email-sender-service:5003"
    depends_on:
      - student-service
      - class-schedule-service
      - notification-service
    networks:
      - app-network

  student-service:
    container_name: student-service
    image: ghcr.io/scholarx-assesment/student-service:latest
    ports:
      - "5001:5001"
    environment:
      DB_HOST: student-service-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: student_db
    depends_on:
      - student-service-db
    networks:
      - app-network

  student-service-db:
    container_name: student-service-db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student_db
    ports:
      - "5433:5432"
    volumes:
      - student_data:/var/lib/postgresql/data
    networks:
      - app-network

  class-schedule-service:
    container_name: class-schedule-service
    image: ghcr.io/scholarx-assesment/class-schedule-service:latest
    ports:
      - "5002:5002"
    environment:
      DB_HOST: class-schedule-service-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: class_schedule_db
    depends_on:
      - class-schedule-service-db
    networks:
      - app-network

  class-schedule-service-db:
    image: postgres:14
    container_name: class-schedule-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: class_schedule_db
    ports:
      - "5434:5432"
    volumes:
      - class_schedule_data:/var/lib/postgresql/data
    networks:
      - app-network

  notification-service:
    container_name: notification-service
    image: ghcr.io/scholarx-assesment/notification-service:latest
    ports:
      - "5003:5003"
    environment:
      DB_HOST: notification-service-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: notification_db
    depends_on:
      - notification-service-db
    networks:
      - app-network

  notification-service-db:
    image: postgres:14
    container_name: notification-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
    ports:
      - "5435:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  student_data:
  class_schedule_data:
  notification_data:
