apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: scholarx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/scholarx-assesment/notification-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: NOTIFICATION_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: notification-postgres-secret
                  key: NOTIFICATION_DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: scholarx-app
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP