apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  namespace: scholarx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: ghcr.io/scholarx-assesment/student-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: STUDENT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: STUDENT_DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: scholarx-app
spec:
  selector:
    app: student-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP